import '../../data/models/event_model.dart';

/// Service for generating test events for development and testing
/// These events showcase different privacy levels and event types
class TestEventsService {
  /// Generate test events for the current month
  /// Includes events with different privacy levels and multiple events per day
  static List<EventModel> generateTestEvents() {
    final now = DateTime.now();
    final currentYear = now.year;
    final currentMonth = now.month;

    return [
      // Day 5 - Multiple events (Work + Other)
      EventModel(
        id: 'test-1',
        userId: 'test-user',
        title: 'Team Standup',
        description: 'Daily team sync meeting',
        startTime: DateTime(currentYear, currentMonth, 5, 9, 0),
        endTime: DateTime(currentYear, currentMonth, 5, 9, 30),
        location: 'Conference Room A',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-2',
        userId: 'test-user',
        title: 'Doctor Appointment',
        description: 'Annual checkup',
        startTime: DateTime(currentYear, currentMonth, 5, 14, 0),
        endTime: DateTime(currentYear, currentMonth, 5, 15, 0),
        location: 'Medical Center',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 10 - Other event
      EventModel(
        id: 'test-3',
        userId: 'test-user',
        title: 'Personal Time',
        description: 'Private personal matters',
        startTime: DateTime(currentYear, currentMonth, 10, 10, 0),
        endTime: DateTime(currentYear, currentMonth, 10, 12, 0),
        location: null,
        visibility: EventVisibility.busyOnly,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 12 - Multiple shared events (Friend + Work)
      EventModel(
        id: 'test-4',
        userId: 'test-user',
        title: 'Lunch with Sarah',
        description: 'Catch up over lunch',
        startTime: DateTime(currentYear, currentMonth, 12, 12, 0),
        endTime: DateTime(currentYear, currentMonth, 12, 13, 0),
        location: 'Downtown Cafe',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-5',
        userId: 'test-user',
        title: 'Project Deadline',
        description: 'Final submission for Q4 project',
        startTime: DateTime(currentYear, currentMonth, 12, 17, 0),
        endTime: DateTime(currentYear, currentMonth, 12, 18, 0),
        location: 'Office',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 15 - All-day holiday event
      EventModel(
        id: 'test-6',
        userId: 'test-user',
        title: 'Christmas Day',
        description: 'Holiday celebration',
        startTime: DateTime(currentYear, currentMonth, 15, 0, 0),
        endTime: DateTime(currentYear, currentMonth, 15, 23, 59, 59),
        location: null,
        visibility: EventVisibility.private,
        category: EventCategory.holiday,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 18 - Multiple events (Other + Work + Friend)
      EventModel(
        id: 'test-7',
        userId: 'test-user',
        title: 'Morning Workout',
        description: 'Gym session',
        startTime: DateTime(currentYear, currentMonth, 18, 6, 0),
        endTime: DateTime(currentYear, currentMonth, 18, 7, 0),
        location: 'Fitness Center',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-8',
        userId: 'test-user',
        title: 'Client Meeting',
        description: 'Quarterly review with client',
        startTime: DateTime(currentYear, currentMonth, 18, 10, 0),
        endTime: DateTime(currentYear, currentMonth, 18, 11, 30),
        location: 'Client Office',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-9',
        userId: 'test-user',
        title: 'Game Night',
        description: 'Board games with friends',
        startTime: DateTime(currentYear, currentMonth, 18, 19, 0),
        endTime: DateTime(currentYear, currentMonth, 18, 22, 0),
        location: 'Mike\'s Place',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 22 - Holiday event with long title
      EventModel(
        id: 'test-10',
        userId: 'test-user',
        title: 'Annual Company Holiday Party and Year-End Celebration',
        description: 'Join us for food, drinks, and festivities',
        startTime: DateTime(currentYear, currentMonth, 22, 18, 0),
        endTime: DateTime(currentYear, currentMonth, 22, 22, 0),
        location: 'Grand Ballroom, Downtown Hotel',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.holiday,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 27 - Other event
      EventModel(
        id: 'test-11',
        userId: 'test-user',
        title: 'Dentist Appointment',
        description: 'Teeth cleaning',
        startTime: DateTime(currentYear, currentMonth, 27, 9, 0),
        endTime: DateTime(currentYear, currentMonth, 27, 10, 0),
        location: 'Dental Clinic',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 20 - Busy day with 10 events (testing overflow)
      EventModel(
        id: 'test-14',
        userId: 'test-user',
        title: 'Morning Standup',
        description: 'Daily sync',
        startTime: DateTime(currentYear, currentMonth, 20, 8, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 8, 30),
        location: 'Office',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-15',
        userId: 'test-user',
        title: 'Design Review',
        description: 'UI mockups',
        startTime: DateTime(currentYear, currentMonth, 20, 9, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 10, 0),
        location: 'Conference Room',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-16',
        userId: 'test-user',
        title: 'Coffee Break with Team',
        description: 'Casual chat',
        startTime: DateTime(currentYear, currentMonth, 20, 10, 30),
        endTime: DateTime(currentYear, currentMonth, 20, 11, 0),
        location: 'Break Room',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-17',
        userId: 'test-user',
        title: 'Client Call',
        description: 'Status update',
        startTime: DateTime(currentYear, currentMonth, 20, 11, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 12, 0),
        location: 'Zoom',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-18',
        userId: 'test-user',
        title: 'Lunch with Alex',
        description: 'Birthday celebration',
        startTime: DateTime(currentYear, currentMonth, 20, 12, 30),
        endTime: DateTime(currentYear, currentMonth, 20, 13, 30),
        location: 'Italian Restaurant',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-19',
        userId: 'test-user',
        title: 'Sprint Planning',
        description: 'Next sprint goals',
        startTime: DateTime(currentYear, currentMonth, 20, 14, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 15, 30),
        location: 'Conference Room A',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-20',
        userId: 'test-user',
        title: 'Doctor Checkup',
        description: 'Annual physical',
        startTime: DateTime(currentYear, currentMonth, 20, 16, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 17, 0),
        location: 'Medical Center',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-21',
        userId: 'test-user',
        title: 'Grocery Shopping',
        description: 'Weekly groceries',
        startTime: DateTime(currentYear, currentMonth, 20, 17, 30),
        endTime: DateTime(currentYear, currentMonth, 20, 18, 30),
        location: 'Whole Foods',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-22',
        userId: 'test-user',
        title: 'Dinner with Friends',
        description: 'Group dinner',
        startTime: DateTime(currentYear, currentMonth, 20, 19, 0),
        endTime: DateTime(currentYear, currentMonth, 20, 21, 0),
        location: 'Steakhouse',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-23',
        userId: 'test-user',
        title: 'New Year Planning',
        description: 'Set goals for next year',
        startTime: DateTime(currentYear, currentMonth, 20, 21, 30),
        endTime: DateTime(currentYear, currentMonth, 20, 22, 30),
        location: 'Home',
        visibility: EventVisibility.private,
        category: EventCategory.other,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),

      // Day 28 - Multiple events (Friend + Work)
      EventModel(
        id: 'test-12',
        userId: 'test-user',
        title: 'Coffee with Mike',
        description: 'Networking coffee',
        startTime: DateTime(currentYear, currentMonth, 28, 8, 0),
        endTime: DateTime(currentYear, currentMonth, 28, 9, 0),
        location: 'Starbucks',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.friend,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
      EventModel(
        id: 'test-13',
        userId: 'test-user',
        title: 'Budget Review Meeting',
        description: 'Q4 financial planning',
        startTime: DateTime(currentYear, currentMonth, 28, 14, 0),
        endTime: DateTime(currentYear, currentMonth, 28, 16, 0),
        location: 'Conference Room B',
        visibility: EventVisibility.sharedWithName,
        category: EventCategory.work,
        nativeCalendarId: null,
        createdAt: DateTime.now(),
      ),
    ];
  }

  /// Check if test events should be loaded
  /// Set this to true during development, false for production
  static const bool enableTestEvents = false;
}
